services:
  backend-dev:
    container_name: riuh_back_dev
    image: riuh_back_dev
    build:
      context: ../
      dockerfile: docker/dockerfiles/back.dockerfile
    ports:
      - 5000:5000
    volumes:
      - ${PROJECT_PATH}/back:/app
    env_file:
      - .env

  frontend-dev:
    container_name: riuh_front_dev
    image: riuh_front_dev
    build:
      context: ../
      dockerfile: docker/dockerfiles/front.dockerfile
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - ${PROJECT_PATH}/front:/app
      - /app/node_modules
    command: npm run dev